[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_GEMINI_API_KEY = "AIzaSyDeUwQfZzVDZPkhKeXHEhDjt6gIYLCpSBk"

[context.deploy-preview.environment]
  VITE_GEMINI_API_KEY = "AIzaSyDeUwQfZzVDZPkhKeXHEhDjt6gIYLCpSBk"
